version: '3.8'

services:
  backend:
    build: ./backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile.dev
    # image: mysql:8.2.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Logger123
      - MYSQL_DATABASE=dashlog
      - MYSQL_USER=Logger
      - MYSQL_PASSWORD=Logger123
    expose:
      - 3307
    ports:
      - 3307:3306
    env_file:
      - ./.env.dev
    
volumes:
  mysql_data: