version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    # command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    command: gunicorn core.wsgi:application -c gunicorn-config.py --no-sendfile
    expose:
      - 7500
    ports:
      - 7999:7500
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile.prod
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    env_file:
      - ./.env.prod.db
  nginx:
    # build: ./nginx
    image: nginx:latest
    ports:
      - 1337:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend
  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/react/build

volumes:
  mysql_data:
  react_build:
